export let infoSemanal = {
    domingo: {
      activate: false,
      hora: {
        hora0: { value: null, completed: null },
        hora1: { value: null, completed: null },
        hora2: { value: null, completed: null },
        hora3: { value: null, completed: null },
        hora4: { value: null, completed: null },
        hora5: { value: null, completed: null },
        hora6: { value: null, completed: null },
        hora7: { value: null, completed: null },
        hora8: { value: null, completed: null },
        hora9: { value: null, completed: null },
        hora10: { value: null, completed: null },
        hora11: { value: null, completed: null },
        hora12: { value: null, completed: null },
        hora13: { value: null, completed: null },
        hora14: { value: null, completed: null },
        hora15: { value: null, completed: null },
        hora16: { value: null, completed: null },
        hora17: { value: null, completed: null },
        hora18: { value: null, completed: null },
        hora19: { value: null, completed: null },
        hora20: { value: null, completed: null },
        hora21: { value: null, completed: null },
        hora22: { value: null, completed: null },
        hora23: { value: null, completed: null },
      },
    },
    lunes: {
      activate: false,
      hora: {
        hora0: { value: null, completed: null },
        hora1: { value: null, completed: null },
        hora2: { value: null, completed: null },
        hora3: { value: null, completed: null },
        hora4: { value: null, completed: null },
        hora5: { value: null, completed: null },
        hora6: { value: null, completed: null },
        hora7: { value: null, completed: null },
        hora8: { value: null, completed: null },
        hora9: { value: null, completed: null },
        hora10: { value: null, completed: null },
        hora11: { value: null, completed: null },
        hora12: { value: null, completed: null },
        hora13: { value: null, completed: null },
        hora14: { value: null, completed: null },
        hora15: { value: null, completed: null },
        hora16: { value: null, completed: null },
        hora17: { value: null, completed: null },
        hora18: { value: null, completed: null },
        hora19: { value: null, completed: null },
        hora20: { value: null, completed: null },
        hora21: { value: null, completed: null },
        hora22: { value: null, completed: null },
        hora23: { value: null, completed: null },
      },
    },
    martes: {
      activate: false,
      hora: {
        hora0: { value:null,completed: null },
        hora1: { value:null,completed: null },
        hora2: { value:null,completed: null },
        hora3: { value:null,completed: null },
        hora4: { value:null,completed: null },
        hora5: { value:null,completed: null },
        hora6: { value:null,completed: null },
        hora7: { value:null,completed: null },
        hora8: { value:null,completed: null },
        hora9: { value:null,completed: null },
        hora10: { value:null,completed: null },
        hora11: { value:null,completed: null },
        hora12: { value:null,completed: null },
        hora13: { value:null,completed: null },
        hora14: { value:null,completed: null },
        hora15: { value:null,completed: null },
        hora16: { value:null,completed: null },
        hora17: { value:null, completed: null },
        hora18: { value:null,completed: null },
        hora19: { value:null,completed: null },
        hora20: { value:null,completed: null },
        hora21: { value:null,completed: null },
        hora22: { value:null,completed: null },
        hora23: { value:null,completed: null },
      },
    },
    miercoles: {
      activate: false,
      hora: {
        hora0: { value: null, completed: null },
        hora1: { value: null, completed: null },
        hora2: { value: null, completed: null },
        hora3: { value: null, completed: null },
        hora4: { value: null, completed: null },
        hora5: { value: null, completed: null },
        hora6: { value: null, completed: null },
        hora7: { value: null, completed: null },
        hora8: { value: null, completed: null },
        hora9: { value: null, completed: null },
        hora10: { value: null, completed: null },
        hora11: { value: null, completed: null },
        hora12: { value: null, completed: null },
        hora13: { value: null, completed: null },
        hora14: { value: null, completed: null },
        hora15: { value: null, completed: null },
        hora16: { value: null, completed: null },
        hora17: { value: null, completed: null },
        hora18: { value: null, completed: null },
        hora19: { value: null, completed: null },
        hora20: { value: null, completed: null },
        hora21: { value: null, completed: null },
        hora22: { value: null, completed: null },
        hora23: { value: null, completed: null },
      },
    },
    jueves: {
      activate: false,
      hora: {
        hora0: { value: null, completed: null },
        hora1: { value: null, completed: null },
        hora2: { value: null, completed: null },
        hora3: { value: null, completed: null },
        hora4: { value: null, completed: null },
        hora5: { value: null, completed: null },
        hora6: { value: null, completed: null },
        hora7: { value: null, completed: null },
        hora8: { value: null, completed: null },
        hora9: { value: null, completed: null },
        hora10: { value: null, completed: null },
        hora11: { value: null, completed: null },
        hora12: { value: null, completed: null },
        hora13: { value: null, completed: null },
        hora14: { value: null, completed: null },
        hora15: { value: null, completed: null },
        hora16: { value: null, completed: null },
        hora17: { value: null, completed: null },
        hora18: { value: null, completed: null },
        hora19: { value: null, completed: null },
        hora20: { value: null, completed: null },
        hora21: { value: null, completed: null },
        hora22: { value: null, completed: null },
        hora23: { value: null, completed: null },
      },
    },
    viernes: {
      activate: false,
      hora: {
        hora0: { value: null, completed: null },
        hora1: { value: null, completed: null },
        hora2: { value: null, completed: null },
        hora3: { value: null, completed: null },
        hora4: { value: null, completed: null },
        hora5: { value: null, completed: null },
        hora6: { value: null, completed: null },
        hora7: { value: null, completed: null },
        hora8: { value: null, completed: null },
        hora9: { value: null, completed: null },
        hora10: { value: null, completed: null },
        hora11: { value: null, completed: null },
        hora12: { value: null, completed: null },
        hora13: { value: null, completed: null },
        hora14: { value: null, completed: null },
        hora15: { value: null, completed: null },
        hora16: { value: null, completed: null },
        hora17: { value: null, completed: null },
        hora18: { value: null, completed: null },
        hora19: { value: null, completed: null },
        hora20: { value: null, completed: null },
        hora21: { value: null, completed: null },
        hora22: { value: null, completed: null },
        hora23: { value: null, completed: null },
      },
    },
    sabado: {
      activate: false,
      hora: {
        hora0: { value: null, completed: null },
        hora1: { value: null, completed: null },
        hora2: { value: null, completed: null },
        hora3: { value: null, completed: null },
        hora4: { value: null, completed: null },
        hora5: { value: null, completed: null },
        hora6: { value: null, completed: null },
        hora7: { value: null, completed: null },
        hora8: { value: null, completed: null },
        hora9: { value: null, completed: null },
        hora10: { value: null, completed: null },
        hora11: { value: null, completed: null },
        hora12: { value: null, completed: null },
        hora13: { value: null, completed: null },
        hora14: { value: null, completed: null },
        hora15: { value: null, completed: null },
        hora16: { value: null, completed: null },
        hora17: { value: null, completed: null },
        hora18: { value: null, completed: null },
        hora19: { value: null, completed: null },
        hora20: { value: null, completed: null },
        hora21: { value: null, completed: null },
        hora22: { value: null, completed: null },
        hora23: { value: null, completed: null },
      },
    },
  };
  

   

    
 (function() {
  let db = JSON.parse(localStorage.getItem("notas"));

  if (!db) {
      localStorage.setItem("notas", JSON.stringify(infoSemanal));
      infoSemanal = JSON.parse(localStorage.getItem("notas"));
  } else {
      infoSemanal = db;
  }

})();
 
 
